Мой первый опыт в латехе, многое сделано НЕОЧЕНЬ. Прошло
нормоконтроль (т.е. шрифты тоже подходят, подрисуночные и прочее), но
сравните со своими требованиями. Результат тоже залил:  [[https://github.com/zarkone/bachelor/vkr-templ.pdf]]

* Описание
- UTF-8
- опции вывода ошибок как в нромальных ЯП, т.е. подхватываются
  например в /Emacs Compilation Mode/
- дополнительные команды в =Makefile=
  
  Вообще, в ВКР я их не использовал, не додумался и не было
  времени. Поэтому на этих исходниках они не будут работать, -- только
  =make build=, =make run=. Однако, потом вот дописалось несколько
  удобных, может вам что-то и пригодится, повыдергивайте на вкус.

* Bugs
в моей версии *LaTeX* нельзя было:

- использовать шрифты Ubuntu Mono
- использовать опцию =--output-directory=build/=, в этом случае =minted=
  при вставке кода не из файла выводил мусор.
- приложение А случайно удалил, инклудилась шаблонная пдфка как у всех

у меня собралось, если что -- пишите куда-нибудь (хоть в issues), попробуем
разобраться. Успехов =)

